tox.c
replaced goto() with a do{}while();
=> removed goto(), and added comments for tox.c tox_thread()

ui.c
=> shrunk the hight of the settings page

win32/main.c, xlib/gtk.c
windows, *nux:
prompt before overwriting
windows:
enforce write ablity via os
TODO:
=> File system enhansements for win32 + *nix

android/main.c, main.h, tox.c, win32/main.c, xlib/main.c
closes notsecure#746 task 1 
@tsudoko
=> support chmod to 600 on unix

xlib/gtk.c
prompts the user on errors
closes notsecure#166
=> utox now checks for write permissions on save file

friend.h, list.c, messages.c, tooltip.c, tooltip.h, ui.c, ui_buttons.h
replaces notsecure#653
and closes notsecure#277
=> Merge of @new-account tooltips, with a little extra on the side

ui_buttons.h
=> hotfix for #774

list.c, tooltip.c, tooltip.h, ui.c, ui.h, win32/main.c, xlib/event.c
- tooltip no longer becomes visible when mouse left window
- tooltip no longer becomes visible when resizing
- tooltip now uses black on white instead of yellow
=> tooltip fixes

Makefile, docs/BUILD.md, docs/INSTALL.md, ui.c
=> Makefile: add support for audio filtering

edit.c, edit.h, ui_edits.h, util.c, util.h, win32/main.c, xlib/event.c, xlib/main.h
I've made tab-completion which works kind of like it does in irssi.
How did I do?
=> Added tab-completion to group chats

avatar.c, avatar.h, dns.c, tox.c, tox_av.h, ui.c, ui_buttons.h, ui_i18n.c, util.c, util.h, win32/audio.c, win32/dnd.c, win32/main.c, xlib/gtk.c, xlib/main.c
This removes all warnings in the code, and fixes a potential memory leak in avatar code.
This also changes code in areas I don't really know about, like the code for sending audio and video, but only in really simple ways. I've been testing whether I can still send video and audio on Xubuntu and Wine and had no problems.
=> remove warnings and fix some problems in avatar code

tox.c
=> save tox_save with STS complient .tox extention

messages.c, tools/cross-compile-windows.sh
closes #820 
introduces bug when selecting text, a url might open when unneeded. I'd rather open the url mistakenly instead of making the user have to restart selecting text or clicking multiple times.
=> Hotfix for #820

docs/BUILD.md
I've had a hard time finding which "filteraudio" is needed, so I thought I'll make it easier for others.
=> Info about dependencies

xlib/event.c
Shift-Insert: paste
Ctrl-Insert: copy
Shift-Delete: cut
=> Added Intel CUA copy/paste shortcuts

xlib/event.c
Ctrl-W to delete last word, like Unix shell.
=> Ctrl-W support

langs/hu.h
=> Hungarian translation: update

docs/INSTALL.md
=> Add info about toxcore.

docs/INSTALL.md
Help DE users adding pretty icon.
=> Add .desktop notes to INSTALLING

Makefile, utox.1
=> Add manpage

langs/lv.h
Updated
- `REQ_SENT`
- `REQ_RESOLVE`
- `CALL_INVITED`
- `CALL_RINGING`
- `WARNING`
- `CONTACTS_FILTER_ONLINE`
- `PROXY_FALLBACK`
- `PROXY_EDIT_HINT_PORT`
=> Latvian translation update

docs/INSTALL.md
- pigon → pigeon
- binarys → binaries
- nightlies → nighties
=> Fix README typos and update formatting

ui_edits.h
People might want to know what they're sending.
=> Show default friend request message if there's no custom one entered

tox.c, tox_transfer.c
=> Adds a bunch of debugging information.

langs/de.h
Grouped in commits for better overview. :de:
=> Updated German translation

list.c
=> Fix group chats sharing the same input buffer

utox.1
- update avatar file info
- fix style inconsistency in the OPTIONS section
- add some basic information about log files
- bump the version
=> Update the man page

langs/fr.h
add french translation for AUDIOFILTERING, SENDSCREENSHOT, MUTE,UNMUTE,THEME, THEME_DEFAULT, THEME_LIGHT, THEME_DARK, THEME_HIGHTCONTRAST
=> add french translation

win32/main.c
=> Prompt to overwrite inline images

tox_av.h
this is the same openal segfault from last year
=> Fixed segfault

Makefile, langs/it.h
=> Italian translation: update

utox.1
It isn't documented anywhere as far as I know. (thanks #977)
Not sure if "Those commands can be used in the chat window." isn't too vague, I can't write very well
=> Add /topic to the man page

theme.c
=> fix truncated hex string in theme.c

langs/fr.h
Add French translation for AVATAR_TOO_LARGE_MAX_SIZE_IS and CANT_FIND_FILE_OR_EMPTY.
=> Update French translation

ui.c
the bitmap isn't big enough for this size anyway
=> fix send button height

theme.h, windows/main.c, xlib/main.c
=> Force show window

Makefile, tools/cross-compile-windows.sh, ui.c
need to add -DGIT_VERSION=\"*\" to compile opts, where * is a git describe command
=> add git version to header of settings to aid in debugging

utox.1
=> Fix minor typo

langs/no.h
Corrected some spelling mistakes.
Translated new items.
Removed tech items which there are no good norwegian words for.
Streamlined with the english translation.
=> Norwegian translation updates

langs/pt.h, ui_i18n.h, ui_i18n_decls.h
Portuguese from Portugal locale.
Hope it follows the guidelines.
Please consider merging.
=> Added Portuguese (pt_PT) translation.

langs/ru.h, xlib/gtk.c
=> update of ru localization file

cocoa/main.m
Not sure:
- what to do with errors instead of abort()
- should this be copypasted over to xlib too?
@GrayHatter fixes #328
=> datapath() should make its dir recursively

avatar.h, button.c, dropdown.c, edit.c, main.h, messages.c, tooltip.c, tox.c, ui.c, windows/main.c, xlib/main.c
Also changed ~~all~~ some occurrences of `colour` to `color` for consistency.
=> Fix comment typos

langs/de.h
=> Update German translations

commands.c, commands.h, friend.c, friend.h, list.c, main.h, tox.c, ui_buttons.h, ui_edits.h, util.c, util.h
todo persist across restarts
closes #190
=> Adds ablity to set an alias for each friend

android/main.c, cocoa/drawing.m, cocoa/grabdesktop.m, cocoa/interaction.m, commands.c, friend.c, list.c, list.h, messages.c, tox.c, ui.c, ui.h, ui_buttons.h, ui_edits.h, windows/dnd.c, windows/main.c, xlib/event.c, xlib/gtk.c, xlib/main.c
The drawing tree was somewhat haphazard in its layout. With some panels called from other, and some separate and enabled/disabled by name only. Now with the current layout, every panel/button/dropdown, just about everything drawable is in a sane tree format meaning each child or parent is easier to find and each can be called without having to interfere or disturb others. 
There are three reasons this is better; First, the layout and flow is much more readable (to me). Second in this format, you can trim and replace parts of the tree as needed. meaning if you want to write a function that will drastically change the skin of µTox, that can be done now without any hacky code. and Finally, by creating a new root panel tree, you can add additional windows without interfering with the primary …
=> User interface code refactor.

cocoa/drawing.m, cocoa/interaction.m, cocoa/main.m
The PTT key was changed to Fn so it wouldn't conflict with the new chat switching shortcuts, which were conflicting with typing special characters.
=> fixed bugs

langs/es.h
Also, here are some questions/suggestions!
- Where are "CALL_INVITED" and "CALL_RINGING" used? I'm not sure how to translate those and it would probably help if I had more context information.
- "Loopback" is a bit of a technical word without an appropriate translation. I'd imagine native English speakers without tech knowledge might be confused by it too.
- "THEME_CUSTOM" is pretty bad, since it doesn't even offer a link to the documentation. It would be pretty cool if uTox could just hide it until a custom theme has been installed, and add a label/link to the specific part of the documentation that explains how to create custom themes.
=> Rewrote Spanish translations
